# Generated by Django 5.2.1 on 2025-05-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
